/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBadge: typeof import('./../components/AppBadge.vue')['default']
    AppButton: typeof import('./../components/AppButton.vue')['default']
    AppSpinnerLoader: typeof import('./../components/AppSpinnerLoader.vue')['default']
    CardSubtext: typeof import('./../components/card/Subtext.vue')['default']
    CardText: typeof import('./../components/card/Text.vue')['default']
    MovieCard: typeof import('./../components/movie/Card.vue')['default']
    MovieCreditsItem: typeof import('./../components/movie/credits/Item.vue')['default']
    MovieCreditsList: typeof import('./../components/movie/credits/List.vue')['default']
    MovieGenres: typeof import('./../components/movie/Genres.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
